/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.ac.unikom.inventorygudang;

import id.ac.unikom.inventorygudang.dao.BarangDAO;
import id.ac.unikom.inventorygudang.dao.DetailBarangDAO;
import id.ac.unikom.inventorygudang.daoimpl.BarangDAOImpl;
import id.ac.unikom.inventorygudang.daoimpl.DetailBarangDAOImpl;
import id.ac.unikom.inventorygudang.entity.Barang;
import id.ac.unikom.inventorygudang.entity.DetailBarang;
import id.ac.unikom.inventorygudang.tablemodel.BarangTM;
import id.ac.unikom.inventorygudang.utility.DatabaseConnectivity;
import java.awt.Color;
import java.awt.Component;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Saeful Rahman
 */
public class FormBarang extends javax.swing.JFrame {

    private Barang barang;
    private ArrayList<Barang> arrayBarang;
    private String namaUser;
    private String hakAkses;
    private int idAdmin;

    //Tipe data untuk memanggil jasper/report
    java.sql.Connection conn;
    JasperReport jasRep;
    JasperPrint jasPri;
    Map param = new HashMap();
    JasperDesign jasDes;
    DatabaseConnectivity koneksi = new DatabaseConnectivity();

    public Barang getBarang() {
        return barang;
    }

    public FormBarang() {
        initComponents();
        refreshData();
    }

    //Konstruktor mengambil data nama dan akses
    public FormBarang(String akses, String nama, int noAdmin) {
        initComponents();
        namaUser = nama;
        hakAkses = akses;
        idAdmin = noAdmin;
        refreshData();
        if (hakAkses.equalsIgnoreCase("Manajer")) {
            btnTambahBarang.setVisible(false);
            btnUbahBarang.setVisible(false);
            btnHapusBarang.setVisible(false);
            btnRefresh.setBounds(40, 100, 100, 60);
        } else if (hakAkses.equalsIgnoreCase("Petugas Gudang")) {
            menuPenjualanBarang.setVisible(false);
            btnCetakLaporan.setVisible(false);
        }
    }

    //Prosedur memanggil data di tabel barang
    private void getData() {
        BarangDAO dao = new BarangDAOImpl();
        arrayBarang = dao.getBarang();

        BarangTM tm = new BarangTM();
        tm.setArrayBarang(arrayBarang);
        tableBarang.setModel(tm);

    }

    //Prosedur memanggail data yang sudah dicari
    private void getData(String cari) {
        BarangDAO dao = new BarangDAOImpl();
        arrayBarang = dao.getBarang(cari);

        BarangTM tm = new BarangTM();
        tm.setArrayBarang(arrayBarang);
        tableBarang.setModel(tm);
    }

    //Prosedur untuk me-merefresh data
    private void refreshData() {
        getData();
    }

    //Prosedur untuk menampilkan report
    private void tampilReport() {
        SimpleDateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        String tanggalHariIni = fmt.format(date);
        try {
            File report = new File("src\\id\\ac\\unikom\\inventorygudang\\report\\ReportBarang.jrxml");
            jasDes = JRXmlLoader.load(report);
            String image = "src\\id\\ac\\unikom\\inventorygudang\\image\\logo-pusdav.png";
            param.put("logo", image);
            param.put("tanggalHariIni", tanggalHariIni);
            jasRep = JasperCompileManager.compileReport(jasDes);
            jasPri = JasperFillManager.fillReport(jasRep, param, koneksi.getConnection());
            JasperViewer.viewReport(jasPri, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelJudul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textAdmin1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBarang = new javax.swing.JTable(){
            public Component prepareRenderer(TableCellRenderer renderer, int row, int col) {
                Component comp = super.prepareRenderer(renderer, row, col);
                if (arrayBarang.get(row).getStok() <= 10) {
                    comp.setBackground(Color.red);
                    comp.setForeground(Color.white);
                }else{
                    comp.setBackground(Color.white);
                    comp.setForeground(Color.black);
                }
                return comp;
            }
        };
        btnHapusBarang = new javax.swing.JButton();
        btnTambahBarang = new javax.swing.JButton();
        btnUbahBarang = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        fieldCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnCetakLaporan = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuKeluar = new javax.swing.JMenuItem();
        menuPenjualan = new javax.swing.JMenu();
        menuUtama = new javax.swing.JMenuItem();
        menuSupplier = new javax.swing.JMenuItem();
        menuPembelian = new javax.swing.JMenuItem();
        menuPenjualanBarang = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventory Gudang");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        labelJudul.setBackground(new java.awt.Color(255, 255, 255));
        labelJudul.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        labelJudul.setForeground(new java.awt.Color(255, 255, 255));
        labelJudul.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelJudul.setText("CV Pusat Dakwah Visual (PUSDAV)");
        labelJudul.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Jln. Diponegoro No. 63, Cihaurgeulis, Cibeunying Kaler, Bandung 40112");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/ac/unikom/inventorygudang/image/logo-pusdav.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(labelJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textAdmin1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        textAdmin1.setForeground(new java.awt.Color(102, 102, 102));
        textAdmin1.setText("Pengolahan Data Barang");

        tableBarang.setBackground(new java.awt.Color(255, 255, 255));
        tableBarang.setForeground(new java.awt.Color(0, 0, 0));
        tableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableBarang);

        btnHapusBarang.setText("Hapus Barang");
        btnHapusBarang.setActionCommand("");
        btnHapusBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnHapusBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusBarangActionPerformed(evt);
            }
        });

        btnTambahBarang.setText("Tambah Barang");
        btnTambahBarang.setActionCommand("");
        btnTambahBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTambahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahBarangActionPerformed(evt);
            }
        });

        btnUbahBarang.setText("Ubah Barang");
        btnUbahBarang.setActionCommand("");
        btnUbahBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUbahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahBarangActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.setActionCommand("");
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnCetakLaporan.setText("Cetak Laporan");
        btnCetakLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakLaporanActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTambahBarang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUbahBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapusBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(fieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textAdmin1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCetakLaporan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKembali)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textAdmin1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCari)
                    .addComponent(fieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambahBarang)
                    .addComponent(btnUbahBarang)
                    .addComponent(btnHapusBarang)
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCetakLaporan)
                    .addComponent(btnKembali))
                .addContainerGap())
        );

        jMenu1.setText("File");

        menuKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/ac/unikom/inventorygudang/image/icon-exit.png"))); // NOI18N
        menuKeluar.setText("Keluar");
        menuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKeluarActionPerformed(evt);
            }
        });
        jMenu1.add(menuKeluar);

        jMenuBar1.add(jMenu1);

        menuPenjualan.setText("Menu");

        menuUtama.setText("Halaman Utama");
        menuUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUtamaActionPerformed(evt);
            }
        });
        menuPenjualan.add(menuUtama);

        menuSupplier.setText("Supplier");
        menuSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSupplierActionPerformed(evt);
            }
        });
        menuPenjualan.add(menuSupplier);

        menuPembelian.setText("Pembelian");
        menuPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPembelianActionPerformed(evt);
            }
        });
        menuPenjualan.add(menuPembelian);

        menuPenjualanBarang.setText("Penjualan");
        menuPenjualanBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenjualanBarangActionPerformed(evt);
            }
        });
        menuPenjualan.add(menuPenjualanBarang);

        jMenuBar1.add(menuPenjualan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusBarangActionPerformed
        int baris = tableBarang.getSelectedRow();
        //Validasi barang yang terpilih
        if (baris >= 0) {
            Barang barangTerpilih = arrayBarang.get(baris);

            int aksiUser = JOptionPane.showConfirmDialog(this, "Apakah Anda "
                    + "yakin akan menghapus data "
                    + barangTerpilih.getNama(), "Hapus Barang ?",
                    JOptionPane.YES_NO_OPTION);
            if (aksiUser == JOptionPane.YES_NO_OPTION) {
                String kode = barangTerpilih.getKodeBarang();
                BarangDAO dao = new BarangDAOImpl();
                DetailBarangDAO daoDetail = new DetailBarangDAOImpl();
                boolean suksesDetail = daoDetail.hapusDetailBarang(kode);
                boolean sukses = dao.hapusBarang(kode);

                if (suksesDetail && sukses) {
                    JOptionPane.showMessageDialog(this, "Barang berhasil dihapus");
                } else {
                    JOptionPane.showMessageDialog(this, "Barang gagal dihapus");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih barang yang akan dihapus");
        }
        getData(null);
    }//GEN-LAST:event_btnHapusBarangActionPerformed

    private void btnTambahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahBarangActionPerformed
        //Menampilkan JDialog Form Tambah Barang
        FormTambahBarang ftb = new FormTambahBarang(null, true);
        ftb.setLocationRelativeTo(null);
        ftb.setVisible(true);
        getData();
    }//GEN-LAST:event_btnTambahBarangActionPerformed

    private void btnUbahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahBarangActionPerformed
        int baris = tableBarang.getSelectedRow();
        //Validasi barang terpilih
        if (baris >= 0) {
            //mengambil data pakaian dari baris tabel
            Barang barangTerpilih = arrayBarang.get(baris);
            FormUbahBarang fub = new FormUbahBarang(null, true, barangTerpilih);
            fub.setLocationRelativeTo(null);
            fub.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Pilih barang yang akan diubah");
        }
        getData();
    }//GEN-LAST:event_btnUbahBarangActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        getData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        //Pencarian
        String cari = fieldCari.getText();
        if (cari != null && !cari.isEmpty()) {
            getData(cari);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Silakan isi pada kolom pencarian");
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnCetakLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakLaporanActionPerformed
        tampilReport();
    }//GEN-LAST:event_btnCetakLaporanActionPerformed

    private void menuSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSupplierActionPerformed
        //Pindah frame ke form supllier
        dispose();
        FormSupplier fs = new FormSupplier(hakAkses, namaUser, idAdmin);
        fs.setLocationRelativeTo(null);
        fs.setVisible(true);
    }//GEN-LAST:event_menuSupplierActionPerformed

    private void menuPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPembelianActionPerformed
        dispose();
        FormPembelian flp = new FormPembelian(hakAkses, namaUser, idAdmin);
        flp.setLocationRelativeTo(null);
        flp.setVisible(true);
    }//GEN-LAST:event_menuPembelianActionPerformed

    private void menuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKeluarActionPerformed
        //Keluar/Logout
        dispose();
        FormLogin fl = new FormLogin(this, true);
        fl.setLocationRelativeTo(null);
        fl.setVisible(true);
    }//GEN-LAST:event_menuKeluarActionPerformed

    private void menuPenjualanBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenjualanBarangActionPerformed
        //Pindah frame ke menu penjualan
        dispose();
        FormPenjualan flp = new FormPenjualan(hakAkses, namaUser, idAdmin);
        flp.setLocationRelativeTo(null);
        flp.setVisible(true);
    }//GEN-LAST:event_menuPenjualanBarangActionPerformed

    private void menuUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUtamaActionPerformed
        dispose();
        FormMenuUtama fmu = new FormMenuUtama(hakAkses, namaUser, idAdmin);
        fmu.setLocationRelativeTo(null);
        fmu.setVisible(true);
    }//GEN-LAST:event_menuUtamaActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        dispose();
        FormMenuUtama fmu = new FormMenuUtama(hakAkses, namaUser, idAdmin);
        fmu.setLocationRelativeTo(null);
        fmu.setVisible(true);
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormBarang fb = new FormBarang();
                fb.setLocationRelativeTo(null);
                fb.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCetakLaporan;
    private javax.swing.JButton btnHapusBarang;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTambahBarang;
    private javax.swing.JButton btnUbahBarang;
    private javax.swing.JTextField fieldCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JMenuItem menuKeluar;
    private javax.swing.JMenuItem menuPembelian;
    private javax.swing.JMenu menuPenjualan;
    private javax.swing.JMenuItem menuPenjualanBarang;
    private javax.swing.JMenuItem menuSupplier;
    private javax.swing.JMenuItem menuUtama;
    private javax.swing.JTable tableBarang;
    public javax.swing.JLabel textAdmin1;
    // End of variables declaration//GEN-END:variables
}
