/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.ac.unikom.inventorygudang;

import id.ac.unikom.inventorygudang.dao.DetailPenjualanDAO;
import id.ac.unikom.inventorygudang.dao.PenjualanDAO;
import id.ac.unikom.inventorygudang.daoimpl.DetailPenjualanDAOImpl;
import id.ac.unikom.inventorygudang.daoimpl.PenjualanDAOImpl;
import id.ac.unikom.inventorygudang.entity.DetailPenjualan;
import id.ac.unikom.inventorygudang.entity.Penjualan;
import id.ac.unikom.inventorygudang.tablemodel.PenjualanTM;
import id.ac.unikom.inventorygudang.utility.DatabaseConnectivity;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Saeful Rahman
 */
public class FormPenjualan extends javax.swing.JFrame {

    private Penjualan penjualan;
    private ArrayList<Penjualan> arrayPenjualan;
    private DetailPenjualan detailPenjualan;
    private ArrayList<DetailPenjualan> arrayDetailPenjualan;
    private String namaUser;
    private String hakAkses;
    private int idAdmin;

    public Penjualan getPenjualan() {
        return penjualan;
    }

    /*
    public DetailPenjualan getDetailPenjualan() {
        return detailPenjualan;
    }
     */
    public FormPenjualan() {
        initComponents();
        refreshData();
    }

    public FormPenjualan(String akses, String nama, int noAdmin) {
        initComponents();
        namaUser = nama;
        hakAkses = akses;
        idAdmin = noAdmin;
        if (hakAkses.equalsIgnoreCase("Manajer")) {
            btnTambahPenjualan.setVisible(false);
        } else if (hakAkses.equalsIgnoreCase("Penjualan")) {
            btnCetakLaporan.setVisible(false);
            menuPenjualan.setVisible(false);
            btnGrafikPenjualan.setVisible(false);
        }
        refreshData();
    }

    private void getData() {
        int totalBrg;
        boolean ketemu = false;
        PenjualanDAO dao = new PenjualanDAOImpl();
        arrayPenjualan = dao.getPenjualan();
        getDetail();

        for (int i = 0; i < arrayPenjualan.size(); i++) {
            totalBrg = 0;
            for (int j = 0; j < arrayDetailPenjualan.size(); j++) {
                if (arrayPenjualan.get(i).getKodePenjualan().equalsIgnoreCase(arrayDetailPenjualan.get(j).getKodePenjualan())) {
                    ketemu = true;
                } else {
                    ketemu = false;
                }
                if (ketemu) {
                    totalBrg = totalBrg + 1;
                }
            }
            arrayPenjualan.get(i).setTotalBrg(totalBrg);
        }

        PenjualanTM tm = new PenjualanTM();
        tm.setArrayPenjualan(arrayPenjualan);
        tablePenjualan.setModel(tm);
    }

    private void getData(String cari) {
        int totalBrg;
        boolean ketemu = false;
        PenjualanDAO dao = new PenjualanDAOImpl();
        arrayPenjualan = dao.getPenjualan(cari);
        getDetail();

        for (int i = 0; i < arrayPenjualan.size(); i++) {
            totalBrg = 0;
            for (int j = 0; j < arrayDetailPenjualan.size(); j++) {
                if (arrayPenjualan.get(i).getKodePenjualan().equalsIgnoreCase(arrayDetailPenjualan.get(j).getKodePenjualan())) {
                    ketemu = true;
                } else {
                    ketemu = false;
                }
                if (ketemu) {
                    totalBrg = totalBrg + 1;
                }
            }
            arrayPenjualan.get(i).setTotalBrg(totalBrg);
        }
        PenjualanTM tm = new PenjualanTM();
        tm.setArrayPenjualan(arrayPenjualan);
        tablePenjualan.setModel(tm);
    }

    private void getDetail() {
        DetailPenjualanDAO dao2 = new DetailPenjualanDAOImpl();
        arrayDetailPenjualan = dao2.getDetailPenjualan();
    }

    private void refreshData() {
        getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textAdmin1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePenjualan = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        fieldCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnCetakLaporan = new javax.swing.JButton();
        btnDetailPenjualan = new javax.swing.JButton();
        btnTambahPenjualan = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelJudul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGrafikPenjualan = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuKeluar = new javax.swing.JMenuItem();
        menuPenjualan = new javax.swing.JMenu();
        menuUtama = new javax.swing.JMenuItem();
        menuBarang = new javax.swing.JMenuItem();
        menuSupplier = new javax.swing.JMenuItem();
        menuPembelian = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventory Gudang");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        textAdmin1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        textAdmin1.setForeground(new java.awt.Color(102, 102, 102));
        textAdmin1.setText("Data Penjualan");

        tablePenjualan.setBackground(new java.awt.Color(255, 255, 255));
        tablePenjualan.setForeground(new java.awt.Color(0, 0, 0));
        tablePenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablePenjualan);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        btnCetakLaporan.setText("Laporan");
        btnCetakLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakLaporanActionPerformed(evt);
            }
        });

        btnDetailPenjualan.setText("Detail Penjualan");
        btnDetailPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailPenjualanActionPerformed(evt);
            }
        });

        btnTambahPenjualan.setText("Tambah Penjualan");
        btnTambahPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahPenjualanActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        labelJudul.setBackground(new java.awt.Color(255, 255, 255));
        labelJudul.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        labelJudul.setForeground(new java.awt.Color(255, 255, 255));
        labelJudul.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelJudul.setText("CV Pusat Dakwah Visual (PUSDAV)");
        labelJudul.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Jln. Diponegoro No. 63, Cihaurgeulis, Cibeunying Kaler, Bandung 40112");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/ac/unikom/inventorygudang/image/logo-pusdav.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(labelJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGrafikPenjualan.setText("Grafik Penjualan");
        btnGrafikPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrafikPenjualanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTambahPenjualan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetailPenjualan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textAdmin1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCetakLaporan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGrafikPenjualan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKembali)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textAdmin1)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCari)
                    .addComponent(fieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh)
                    .addComponent(btnDetailPenjualan)
                    .addComponent(btnTambahPenjualan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCetakLaporan)
                    .addComponent(btnKembali)
                    .addComponent(btnGrafikPenjualan))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        menuKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/ac/unikom/inventorygudang/image/icon-exit.png"))); // NOI18N
        menuKeluar.setText("Keluar");
        menuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKeluarActionPerformed(evt);
            }
        });
        jMenu1.add(menuKeluar);

        jMenuBar1.add(jMenu1);

        menuPenjualan.setText("Menu");

        menuUtama.setText("Halaman Utama");
        menuUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUtamaActionPerformed(evt);
            }
        });
        menuPenjualan.add(menuUtama);

        menuBarang.setText("Barang");
        menuBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBarangActionPerformed(evt);
            }
        });
        menuPenjualan.add(menuBarang);

        menuSupplier.setText("Supplier");
        menuSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSupplierActionPerformed(evt);
            }
        });
        menuPenjualan.add(menuSupplier);

        menuPembelian.setText("Pembelian");
        menuPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPembelianActionPerformed(evt);
            }
        });
        menuPenjualan.add(menuPembelian);

        jMenuBar1.add(menuPenjualan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        getData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        String cari = fieldCari.getText();
        if (cari != null && !cari.isEmpty()) {
            getData(cari);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Silakan isi pada kolom pencarian");
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnCetakLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakLaporanActionPerformed
        FormDetailLaporanPenjualan fdlp = new FormDetailLaporanPenjualan(this, true);
        fdlp.setLocationRelativeTo(null);
        fdlp.setVisible(true);
    }//GEN-LAST:event_btnCetakLaporanActionPerformed

    private void menuSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSupplierActionPerformed
        dispose();
        FormSupplier fs = new FormSupplier(hakAkses, namaUser, idAdmin);
        fs.setLocationRelativeTo(null);
        fs.setVisible(true);
    }//GEN-LAST:event_menuSupplierActionPerformed

    private void menuBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarangActionPerformed
        dispose();
        FormBarang fb = new FormBarang(hakAkses, namaUser, idAdmin);
        fb.setLocationRelativeTo(null);
        fb.setVisible(true);
    }//GEN-LAST:event_menuBarangActionPerformed

    private void menuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKeluarActionPerformed
        dispose();
        FormLogin fl = new FormLogin(this, true);
        fl.setLocationRelativeTo(null);
        fl.setVisible(true);
    }//GEN-LAST:event_menuKeluarActionPerformed

    private void menuPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPembelianActionPerformed
        dispose();
        FormPembelian flp = new FormPembelian(hakAkses, namaUser, idAdmin);
        flp.setLocationRelativeTo(null);
        flp.setVisible(true);
    }//GEN-LAST:event_menuPembelianActionPerformed

    private void menuUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUtamaActionPerformed
        dispose();
        FormMenuUtama fmu = new FormMenuUtama(hakAkses, namaUser, idAdmin);
        fmu.setLocationRelativeTo(null);
        fmu.setVisible(true);
    }//GEN-LAST:event_menuUtamaActionPerformed

    private void btnDetailPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailPenjualanActionPerformed
        int baris = tablePenjualan.getSelectedRow();
        if (baris >= 0) {
            Penjualan dataTerpilih = arrayPenjualan.get(baris);
            FormDetailPenjualan fdpn = new FormDetailPenjualan(this, true, dataTerpilih);
            fdpn.setLocationRelativeTo(null);
            fdpn.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Pilih daata pada tabel"
                    + " penjualan");
        }
    }//GEN-LAST:event_btnDetailPenjualanActionPerformed

    private void btnTambahPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahPenjualanActionPerformed
        dispose();
        FormTambahPenjualan ftp = new FormTambahPenjualan(hakAkses, namaUser, idAdmin);
        ftp.setLocationRelativeTo(null);
        ftp.setVisible(true);
    }//GEN-LAST:event_btnTambahPenjualanActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        dispose();
        FormMenuUtama fmu = new FormMenuUtama(hakAkses, namaUser, idAdmin);
        fmu.setLocationRelativeTo(null);
        fmu.setVisible(true);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnGrafikPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrafikPenjualanActionPerformed
        DefaultCategoryDataset dcd = new DefaultCategoryDataset();
        boolean sama = false;
        for (int i = 0; i < arrayPenjualan.size(); i++) {
            int jml = 0;
            Penjualan penjualan = new Penjualan();
            penjualan = arrayPenjualan.get(i);
            for (int k = 0; k < arrayPenjualan.size(); k++) {
                Penjualan penjualan2 = new Penjualan();
                penjualan2 = arrayPenjualan.get(k);
                String tgl1 = String.valueOf(penjualan.getTglJual());
                String tgl2 = String.valueOf(penjualan2.getTglJual());
                if (tgl1.equals(tgl2)) {
                    sama = true;
                }

                if (sama) {
                    jml = jml + penjualan2.getTotalBrg();
                    sama = false;
                }
            }
            String tanggal = String.valueOf(penjualan.getTglJual());
            dcd.setValue(jml, "Barang", tanggal);
        }
        JFreeChart freeChart = ChartFactory.createBarChart("Grafik Penjualan", "Tanggal", "Jumlah Barang", dcd, PlotOrientation.HORIZONTAL, true, true, true); //String arg0,String arg1,String arg2,Category Datasheet,Plot Orientation,boolean arg4,boolean arg5,boolean arg6
        ChartFrame cf = new ChartFrame("Data Penjualan PUSDAV", freeChart);

        cf.setSize(1000, 500);
        cf.setVisible(true);
        cf.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnGrafikPenjualanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormPenjualan fb = new FormPenjualan();
                fb.setLocationRelativeTo(null);
                fb.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCetakLaporan;
    private javax.swing.JButton btnDetailPenjualan;
    private javax.swing.JButton btnGrafikPenjualan;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTambahPenjualan;
    private javax.swing.JTextField fieldCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JMenuItem menuBarang;
    private javax.swing.JMenuItem menuKeluar;
    private javax.swing.JMenuItem menuPembelian;
    private javax.swing.JMenu menuPenjualan;
    private javax.swing.JMenuItem menuSupplier;
    private javax.swing.JMenuItem menuUtama;
    private javax.swing.JTable tablePenjualan;
    public javax.swing.JLabel textAdmin1;
    // End of variables declaration//GEN-END:variables
}
